AWSTemplateFormatVersion: 2010-09-09
Resources:
    ShareHotWaterRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -   Effect: Allow
                        Principal:
                            Service: lambda.amazonaws.com
                        Action: "sts:AssumeRole"
    ShareHotWaterFunction:
        Type: 'AWS::Lambda::Function'
        Properties:
            Code: ./lambda_function.py
            Environment:
                Variables:
                    UserToken: xoxp-xxxxxxxxxxxxxxx
                    BotToken: xoxb-xxxxxxxxxxxxxxx
                    DelayMinute: 5
                    PostChannel: CXXXXXXXX
            Handler: lambda_function.lambda_handler
            Role: !GetAtt ShareHotWaterRole.Arn
            Runtime: python3.6
